-- Repair historical orphan rows before enforcing relational constraints.
DELETE FROM order_items oi
WHERE oi.order_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.id = oi.order_id);

DELETE FROM order_items oi
WHERE oi.product_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM products p WHERE p.id = oi.product_id);

DELETE FROM reviews r
WHERE r.product_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM products p WHERE p.id = r.product_id);

-- Schema migration for existing orders to support coupon discount amount

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS discount_amount numeric(38,2);

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS delay_flag boolean NOT NULL DEFAULT false;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS delivery_charge numeric(38,2) NOT NULL DEFAULT 0;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS offer_discount numeric(38,2) NOT NULL DEFAULT 0;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS subtotal numeric(38,2) NOT NULL DEFAULT 0;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS tax numeric(38,2) NOT NULL DEFAULT 0;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS display_priority integer NOT NULL DEFAULT 0;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS show_in_todays_offers boolean NOT NULL DEFAULT false;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS mobile_verified boolean NOT NULL DEFAULT false;

-- Add store logo column for persisting uploaded logo URL
ALTER TABLE store_settings
    ADD COLUMN IF NOT EXISTS logo varchar(255);

-- Increase product image URL length to accommodate long external links
ALTER TABLE products
    ALTER COLUMN image TYPE varchar(2000);

ALTER TABLE product_images
    ALTER COLUMN image_url TYPE varchar(2000);

UPDATE orders
    SET discount_amount = 0
    WHERE discount_amount IS NULL;

ALTER TABLE orders
    ALTER COLUMN discount_amount SET NOT NULL;

CREATE TABLE IF NOT EXISTS banners (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    subtitle varchar(255),
    image_url varchar(255),
    link_to varchar(255),
    active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

CREATE TABLE IF NOT EXISTS serviceable_pincodes (
    id bigint generated by default as identity primary key,
    pincode varchar(10) not null unique
);

-- Seed Greater Austin serviceable ZIP codes.
INSERT INTO serviceable_pincodes (pincode)
VALUES
    ('78701'), ('78702'), ('78703'), ('78704'), ('78705'), ('78712'), ('78717'), ('78719'),
    ('78721'), ('78722'), ('78723'), ('78724'), ('78725'), ('78726'), ('78727'), ('78728'),
    ('78729'), ('78730'), ('78731'), ('78732'), ('78733'), ('78734'), ('78735'), ('78736'),
    ('78737'), ('78738'), ('78739'), ('78741'), ('78742'), ('78744'), ('78745'), ('78746'),
    ('78747'), ('78748'), ('78749'), ('78750'), ('78751'), ('78752'), ('78753'), ('78754'),
    ('78756'), ('78757'), ('78758'), ('78759'), ('78760'), ('78761'), ('78762'), ('78763'),
    ('78764'), ('78765'), ('78766'), ('78767'), ('78768'), ('78769'), ('78772'), ('78773'),
    ('78774'), ('78778'), ('78779'), ('78780'), ('78781'), ('78783'), ('78785'), ('78786'),
    ('78788'), ('78789'), ('78790'), ('78791'), ('78792'), ('78799')
ON CONFLICT (pincode) DO NOTHING;

CREATE TABLE IF NOT EXISTS product_events (
    id bigint generated by default as identity primary key,
    product_id varchar(255) not null,
    type varchar(32) not null,
    created_at timestamp(6) not null
);
