-- Schema migration for existing orders to support coupon discount amount

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS discount_amount numeric(38,2);

UPDATE orders
    SET discount_amount = 0
    WHERE discount_amount IS NULL;

ALTER TABLE orders
    ALTER COLUMN discount_amount SET NOT NULL;

CREATE TABLE IF NOT EXISTS banners (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    subtitle varchar(255),
    image_url varchar(255),
    link_to varchar(255),
    active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);
