-- Schema migration for existing orders to support coupon discount amount

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS discount_amount numeric(38,2);

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS delay_flag boolean NOT NULL DEFAULT false;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS delivery_charge numeric(38,2) NOT NULL DEFAULT 0;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS offer_discount numeric(38,2) NOT NULL DEFAULT 0;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS subtotal numeric(38,2) NOT NULL DEFAULT 0;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS tax numeric(38,2) NOT NULL DEFAULT 0;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS display_priority integer NOT NULL DEFAULT 0;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS show_in_todays_offers boolean NOT NULL DEFAULT false;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS mobile_verified boolean NOT NULL DEFAULT false;

UPDATE orders
    SET discount_amount = 0
    WHERE discount_amount IS NULL;

ALTER TABLE orders
    ALTER COLUMN discount_amount SET NOT NULL;

CREATE TABLE IF NOT EXISTS banners (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    subtitle varchar(255),
    image_url varchar(255),
    link_to varchar(255),
    active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

CREATE TABLE IF NOT EXISTS serviceable_pincodes (
    id bigint generated by default as identity primary key,
    pincode varchar(10) not null unique
);

CREATE TABLE IF NOT EXISTS product_events (
    id bigint generated by default as identity primary key,
    product_id varchar(255) not null,
    type varchar(32) not null,
    created_at timestamp(6) not null
);
